### ISSUE TITLE
Use the full space

### ISSUE THREAD

**Issue by ShalokShalom** [Felli/humhub-themes-flathub#7]
Are there any ideas around, how to use the full space here?

![1](https://cloud.githubusercontent.com/assets/6344099/21587332/61b9560e-d0db-11e6-906c-af7f4f0bf9a0.png)

**Comment by Felli** [comment]
Hmm... You could always edit the CSS files to fill the screen rather than fit it.

**Comment by ShalokShalom** [comment]
I mean, is this in everybodys interested?

Nice default?

**Comment by Felli** [comment]
I would prefer responsive overall, would make for better mobile use. Changing the columns to fit would most likely mess with mobile users more than web users, but at the moment this theme is about 80% responsive, still need to fix some issues, one being the other 20% not being responsive. I'm always looking for people to help out where it's needed. :+1:

**Comment by ShalokShalom** [comment]
Can the sidemenus scroll with?

**Comment by Felli** [comment]
It is possible but you would have to create a JavaScript file yourself, then make sure that you add onto the [head.php](https://github.com/Felli/humhub-themes-flathub/blob/master/views/layouts/head.php#L6) file. :+1: 

The best example would be [here](https://css-tricks.com/scrollfollow-sidebar/). :smiley:

**Comment by Felli** [comment]
Closing because questions were answered. :+1:
